# Generated by Django 2.2.1 on 2019-05-27 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20190527_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='multiple_choice_answer',
            new_name='is_multiple_choice_answer',
        ),
    ]
