# Generated by Django 2.2.1 on 2019-05-29 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20190528_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionchoice',
            old_name='text',
            new_name='option',
        ),
    ]
