# Generated by Django 2.2.1 on 2019-05-30 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_auto_20190530_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='required',
        ),
    ]
