# Generated by Django 2.2.1 on 2019-06-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_remove_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='order',
            field=models.IntegerField(),
        ),
    ]
