# Generated by Django 2.2.1 on 2019-06-05 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20190603_0732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
