# Generated by Django 2.2.1 on 2019-06-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses',
                                   to='api.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses',
                                               to='api.Question')),
                ('survey_response',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses',
                                   to='api.SurveyResponse')),
            ],
        ),
    ]
