# Generated by Django 2.2.1 on 2019-06-11 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_response_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='survey_responses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='survey_response',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses',
                                    to='api.SurveyResponse'),
        ),
    ]
